---
title: "sim_result_report_small"
author: "Yu Yan"
date: "2024-02-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(error = F)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)

#knitr::opts_chunk$set(fig.width=8, fig.height=4) 
library(tidyverse)
library(kableExtra)
library(mice)
library(gtsummary)
library(psych)
library(ggridges)
library(writexl)
```



```{r}
# new algo result
# running new algo on milp-type data
new_alg <- read_csv('testing_2024.2.26_new.csv')
# parameter columns
new_alg <- new_alg %>% mutate(p1 = unlist(lapply(new_alg$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[3])
  })), 
                                   p2 = unlist(lapply(new_alg$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[4])
  })),
                                   eps = unlist(lapply(new_alg$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[5])
  })),
                                   link = unlist(lapply(new_alg$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[6])
  })))
```

```{r}
# ncd result
# running cyclical coordinate descent algo on milp-type data
ncd <- read_csv('ncd_cv0_R_loop_milpdat.csv')
# parameter columns
ncd <- ncd %>% mutate(p1 = unlist(lapply(ncd$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[3])
  })), 
                                   p2 = unlist(lapply(ncd$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[4])
  })),
                                   eps = unlist(lapply(ncd$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[5])
  })),
                                   link = unlist(lapply(ncd$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[6])
  })))
```

```{r}
# round logistic
# running round logistic algo on milp-type data
logis <- read_csv('results_ncd_fr_milp_2.26.csv')

logis <- logis[logis$method=='Round',]
indices <- match(new_alg$data,logis$data)
logis <- logis[indices,]
# parameter columns
logis <- logis %>% mutate(p1 = unlist(lapply(logis$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[3])
  })), 
                                   p2 = unlist(lapply(logis$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[4])
  })),
                                   eps = unlist(lapply(logis$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[5])
  })),
                                   link = unlist(lapply(logis$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[6])
  })))
```

```{r}
# milp_v2 result (time_limit = 3600s)
# running milp_v2 on milp_type data 
milp_v2_r1 <- read_csv('results_milp_v2_testing_2.24_t_limit.csv')
milp_v2_r2 <- read_csv("results_milp_v2_testing_2.28_t_7200.csv")


# parameter columns
milp_v2_r1 <- milp_v2_r1 %>% mutate(p1 = unlist(lapply(milp_v2_r1$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[3])
  })), 
                                   p2 = unlist(lapply(milp_v2_r1$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[4])
  })),
                                   eps = unlist(lapply(milp_v2_r1$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[5])
  })),
                                   link = unlist(lapply(milp_v2_r1$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[6])
  })))


milp_v2_r2 <- milp_v2_r2 %>% mutate(p1 = unlist(lapply(milp_v2_r2$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[3])
  })), 
                                   p2 = unlist(lapply(milp_v2_r2$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[4])
  })),
                                   eps = unlist(lapply(milp_v2_r2$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[5])
  })),
                                   link = unlist(lapply(milp_v2_r2$data, function(input_string) {
  split_string <- unlist(strsplit(input_string, "_"))
  return(split_string[6])
  })))

milp_v2_r1 %>% summarise(acc = mean(acc))
milp_v2_r1 %>% group_by(link) %>%  summarise(opt = mean(gap))
milp_v2_r2 %>% summarise(acc = mean(acc))

```

```{r}

milp_v2_r1  %>% group_by(link) %>%
  summarise(acc = mean(acc),
            auc = mean(auc),
            sens = mean(sens),
            spec = mean(spec),
            time = mean(time),
            gap = mean(gap),
            status = sum(status=='optimal'))


# t limit 7200
milp_v2_r2  %>% group_by(link) %>%
  summarise(acc = mean(acc),
            auc = mean(auc),
            sens = mean(sens),
            spec = mean(spec),
            time = mean(time),
            gap = mean(gap),
            status = sum(status=='optimal'))
```

# Results Summary
```{r}
# acc comparison
acc_dat <- as.data.frame(cbind(new_alg$acc,ncd$acc,logis$acc,milp_v2_r1$acc ,new_alg$link)) %>%
  set_names(c('new','ncd','logis','milp_v2','link')) %>%
  pivot_longer(c(new,ncd,logis,milp_v2), names_to = 'alg',values_to = 'acc') %>%
  mutate(acc=as.numeric(acc),alg=as.factor(alg),link=as.numeric(link)) 



# display
acc_dat %>% 
  tbl_strata(
    strata = alg,
    .tbl_fun =
      ~ .x %>%
      tbl_summary(by = link,
        type = list(acc ~ 'continuous'),
    statistic = list(all_continuous() ~ "{mean}({sd})"),
    digits = list(acc ~ c(3, 3))),
    .header = "**{strata}**" 
  ) %>% # convert to kableExtra
  as_kable_extra(booktabs = TRUE, caption = "Acc Comparison") %>%
  # reduce font size to make table fit. 
  kableExtra::kable_styling(full_width = T, font_size = 7)
```

```{r}
# sec vs acc
sec_dat <- as.data.frame(cbind(new_alg$sec,ncd$sec,logis$time,milp_v2$time,new_alg$link)) %>% 
  set_names(c('new','ncd','logis','milp_v2','link')) %>% 
  pivot_longer(c(new,ncd,logis,milp_v2), names_to = 'alg',values_to = 'sec') %>%
  mutate(sec=as.numeric(sec),alg=as.factor(alg),link=as.numeric(link)) 

sec_acc_dat <- bind_cols(acc_dat,sec_dat,.name_repair = 'minimal') 

sec_acc_dat[,-c(4,5)] %>% ggplot(aes(x=acc,y=sec,color=alg)) +
  geom_line()
```


```{r}

```

